# Generated by Django 4.0.3 on 2022-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
